import type {
  Service,
  Order,
  Address,
  Profile,
  Coupon,
  SubscriptionPlan,
  LoyaltyAccount,
  ServiceArea,
  SupportTicket,
} from '../types';

export const INITIAL_PROFILES: Record<string, Profile> = {
  customer: {
    id: 'user_cust_01',
    email: 'aditi.sharma@gmail.com',
    full_name: 'Aditi Sharma',
    phone: '+91 98450 12345',
    role: 'customer',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  pickup_staff: {
    id: 'user_pickup_01',
    email: 'vikram.singh@freshfold.in',
    full_name: 'Vikram Singh (Rider #14)',
    phone: '+91 98765 43210',
    role: 'pickup_staff',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  laundry_staff: {
    id: 'user_facility_01',
    email: 'sunita.patel@freshfold.in',
    full_name: 'Sunita Patel (Facility Lead)',
    phone: '+91 99887 76655',
    role: 'laundry_staff',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  delivery_staff: {
    id: 'user_delivery_01',
    email: 'amit.kumar@freshfold.in',
    full_name: 'Amit Kumar (Courier #08)',
    phone: '+91 98112 34567',
    role: 'delivery_staff',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  admin: {
    id: 'user_admin_01',
    email: 'operations@freshfold.in',
    full_name: 'Command Tower Admin',
    phone: '+91 80 4040 5000',
    role: 'admin',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
};

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv_wash_fold',
    name: 'Wash & Eco-Fold',
    description: 'Separated whites & colors, hypoallergenic wash, tumble dried, and laser-precise folding ready for the closet.',
    category: 'wash_fold',
    pricing_type: 'per_kg',
    base_price: 69,
    minimum_quantity: 3,
    maximum_quantity: 20,
    express_surcharge: 120,
    turnaround_hours: 24,
    popular: true,
    tag: 'Bestseller',
  },
  {
    id: 'srv_wash_iron',
    name: 'Wash & Steam Iron',
    description: 'Enzyme-rich gentle wash followed by commercial 3-bar steam pressing for crisp, wrinkle-free collars and pleats.',
    category: 'wash_iron',
    pricing_type: 'per_kg',
    base_price: 99,
    minimum_quantity: 3,
    maximum_quantity: 20,
    express_surcharge: 150,
    turnaround_hours: 24,
    popular: true,
    tag: 'Recommended',
  },
  {
    id: 'srv_iron_only',
    name: 'Steam Press Only',
    description: 'High-temperature sanitize and steam press for clean garments requiring crisp, zero-wrinkle corporate perfection.',
    category: 'iron_only',
    pricing_type: 'per_item',
    base_price: 25,
    minimum_quantity: 5,
    maximum_quantity: 30,
    express_surcharge: 80,
    turnaround_hours: 12,
  },
  {
    id: 'srv_dry_clean',
    name: 'Artisan Dry Cleaning',
    description: 'Perchloroethylene-free organic solvent treatment tailored for silks, suits, blazers, designer lehengas, and wool.',
    category: 'dry_clean',
    pricing_type: 'per_item',
    base_price: 180,
    minimum_quantity: 1,
    maximum_quantity: 15,
    express_surcharge: 200,
    turnaround_hours: 48,
    popular: false,
    tag: 'Premium',
  },
  {
    id: 'srv_premium_care',
    name: 'Silk & Delicate Spa',
    description: 'Hand-washed in temperature-monitored baths using Swedish woolmark-certified liquid botanicals.',
    category: 'premium_care',
    pricing_type: 'per_kg',
    base_price: 249,
    minimum_quantity: 2,
    maximum_quantity: 10,
    express_surcharge: 250,
    turnaround_hours: 48,
  },
  {
    id: 'srv_shoe_spa',
    name: 'Sneaker & Shoe Revival',
    description: 'Deep foam scrub, suede revitalization, internal UV ozone sanitization, and waterproof nano-coating.',
    category: 'spa',
    pricing_type: 'per_item',
    base_price: 299,
    minimum_quantity: 1,
    maximum_quantity: 10,
    express_surcharge: 150,
    turnaround_hours: 48,
  },
];

export const INITIAL_ADDRESSES: Address[] = [
  {
    id: 'addr_01',
    user_id: 'user_cust_01',
    name: 'Aditi Sharma',
    phone: '+91 98450 12345',
    address_line: 'Tower 4, Flat 1202, Prestige Lakeside Habitat',
    landmark: 'Near Varthur Lake',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560087',
    address_type: 'home',
    is_default: true,
  },
  {
    id: 'addr_02',
    user_id: 'user_cust_01',
    name: 'Aditi Sharma (Office)',
    phone: '+91 98450 12345',
    address_line: 'WeWork Galaxy, 43 Residency Road, Shanthala Nagar',
    landmark: 'Opposite Chancery Pavilion',
    city: 'Bengaluru',
    state: 'Karnataka',
    postal_code: '560025',
    address_type: 'work',
    is_default: false,
  },
];

export const INITIAL_SERVICE_AREAS: ServiceArea[] = [
  { postal_code: '560087', city: 'Bengaluru', area_name: 'Whitefield / Varthur', is_active: true, delivery_sla_hours: 24 },
  { postal_code: '560025', city: 'Bengaluru', area_name: 'Residency Rd / Ashok Nagar', is_active: true, delivery_sla_hours: 24 },
  { postal_code: '560034', city: 'Bengaluru', area_name: 'Koramangala 4th Block', is_active: true, delivery_sla_hours: 24 },
  { postal_code: '560102', city: 'Bengaluru', area_name: 'HSR Layout Sector 1-7', is_active: true, delivery_sla_hours: 24 },
  { postal_code: '560001', city: 'Bengaluru', area_name: 'MG Road / Brigade', is_active: true, delivery_sla_hours: 24 },
  { postal_code: '110001', city: 'New Delhi', area_name: 'Connaught Place', is_active: true, delivery_sla_hours: 36 },
  { postal_code: '400001', city: 'Mumbai', area_name: 'Fort / Nariman Point', is_active: true, delivery_sla_hours: 36 },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'FF-74102',
    user_id: 'user_cust_01',
    customer_name: 'Aditi Sharma',
    customer_phone: '+91 98450 12345',
    address: INITIAL_ADDRESSES[0],
    status: 'PICKUP_ASSIGNED',
    items: [
      {
        id: 'item_1',
        service_id: 'srv_wash_fold',
        service_name: 'Wash & Eco-Fold',
        quantity: 1,
        weight: 4.5,
        unit_price: 69,
        total_price: 310,
        special_instructions: 'Separate darks; use mild citrus fragrance',
      },
    ],
    subtotal: 310,
    discount_amount: 50,
    delivery_charge: 0,
    express_surcharge: 0,
    total_amount: 260,
    payment_status: 'PAID',
    payment_method: 'razorpay',
    coupon_code: 'FRESH50',
    loyalty_points_used: 0,
    loyalty_points_earned: 26,
    pickup_slot_date: 'Today',
    pickup_slot_time: '10:00 AM - 12:00 PM',
    estimated_delivery: 'Tomorrow, 7:00 PM',
    delivery_pin: '4821',
    notes: 'Please buzz 1202 at gate security',
    pickup_staff_id: 'user_pickup_01',
    pickup_staff_name: 'Vikram Singh (Rider #14)',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 1800000).toISOString(),
    history: [
      {
        id: 'h1',
        status: 'ORDER_PLACED',
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        note: 'Order confirmed online via Razorpay',
        actor: 'Aditi Sharma',
      },
      {
        id: 'h2',
        status: 'PICKUP_ASSIGNED',
        timestamp: new Date(Date.now() - 1800000).toISOString(),
        note: 'Assigned to nearest hub rider Vikram Singh',
        actor: 'Dispatcher AI',
      },
    ],
  },
  {
    id: 'FF-63914',
    user_id: 'user_cust_01',
    customer_name: 'Aditi Sharma',
    customer_phone: '+91 98450 12345',
    address: INITIAL_ADDRESSES[0],
    status: 'WASHING',
    laundry_stage: 'WASHING',
    bag_id: 'BAG-8824',
    measured_weight_kg: 5.2,
    items: [
      {
        id: 'item_2',
        service_id: 'srv_wash_iron',
        service_name: 'Wash & Steam Iron',
        quantity: 1,
        weight: 5.2,
        unit_price: 99,
        total_price: 514,
        special_instructions: 'Starch cuffs on white shirts lightly',
      },
    ],
    subtotal: 514,
    discount_amount: 0,
    delivery_charge: 40,
    express_surcharge: 0,
    total_amount: 554,
    payment_status: 'PAID',
    payment_method: 'upi',
    loyalty_points_used: 0,
    loyalty_points_earned: 55,
    pickup_slot_date: 'Yesterday',
    pickup_slot_time: '2:00 PM - 4:00 PM',
    estimated_delivery: 'Today, 8:00 PM',
    delivery_pin: '7392',
    pickup_staff_id: 'user_pickup_01',
    pickup_staff_name: 'Vikram Singh',
    created_at: new Date(Date.now() - 3600000 * 22).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    history: [
      {
        id: 'h2_1',
        status: 'ORDER_PLACED',
        timestamp: new Date(Date.now() - 3600000 * 22).toISOString(),
        note: 'Order placed',
      },
      {
        id: 'h2_2',
        status: 'PICKED_UP',
        timestamp: new Date(Date.now() - 3600000 * 18).toISOString(),
        note: 'Collected 5.2 kg garments in sealed bag BAG-8824',
        actor: 'Vikram Singh',
      },
      {
        id: 'h2_3',
        status: 'RECEIVED_AT_FACILITY',
        timestamp: new Date(Date.now() - 3600000 * 14).toISOString(),
        note: 'Weighed & checked in at Hub North #2',
        actor: 'Sunita Patel',
      },
      {
        id: 'h2_4',
        status: 'SORTING',
        timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
        note: 'Sorted into Cotton Wash Batch #C4',
        actor: 'Sunita Patel',
      },
      {
        id: 'h2_5',
        status: 'WASHING',
        timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
        note: 'Eco wash cycle started at 30°C',
        actor: 'Sunita Patel',
      },
    ],
  },
  {
    id: 'FF-82015',
    user_id: 'user_cust_01',
    customer_name: 'Aditi Sharma',
    customer_phone: '+91 98450 12345',
    address: INITIAL_ADDRESSES[0],
    status: 'OUT_FOR_DELIVERY',
    bag_id: 'BAG-4190',
    measured_weight_kg: 3.8,
    items: [
      {
        id: 'item_3',
        service_id: 'srv_dry_clean',
        service_name: 'Artisan Dry Cleaning (2x Suits)',
        quantity: 2,
        unit_price: 180,
        total_price: 360,
      },
    ],
    subtotal: 360,
    discount_amount: 100,
    delivery_charge: 0,
    express_surcharge: 0,
    total_amount: 260,
    payment_status: 'PAID',
    payment_method: 'card',
    coupon_code: 'CLEAN100',
    loyalty_points_used: 0,
    loyalty_points_earned: 26,
    pickup_slot_date: '2 days ago',
    pickup_slot_time: '11:00 AM',
    estimated_delivery: 'Within 30 mins',
    delivery_pin: '1947',
    delivery_staff_id: 'user_delivery_01',
    delivery_staff_name: 'Amit Kumar (Courier #08)',
    quality_check: {
      stain_removal: true,
      collar_cuff: true,
      fabric_softness: true,
      fragrance: true,
      folding_neatness: true,
      eco_packaging: true,
      damage_detected: false,
      inspector_name: 'Sunita Patel',
      inspected_at: new Date(Date.now() - 7200000).toISOString(),
      passed: true,
    },
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    updated_at: new Date(Date.now() - 1200000).toISOString(),
    history: [
      { id: 'h3_1', status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 3600000 * 48).toISOString() },
      { id: 'h3_2', status: 'PICKED_UP', timestamp: new Date(Date.now() - 3600000 * 44).toISOString() },
      { id: 'h3_3', status: 'RECEIVED_AT_FACILITY', timestamp: new Date(Date.now() - 3600000 * 40).toISOString() },
      { id: 'h3_4', status: 'QUALITY_CHECK', timestamp: new Date(Date.now() - 3600000 * 8).toISOString() },
      { id: 'h3_5', status: 'READY_FOR_DELIVERY', timestamp: new Date(Date.now() - 3600000 * 4).toISOString() },
      {
        id: 'h3_6',
        status: 'OUT_FOR_DELIVERY',
        timestamp: new Date(Date.now() - 1200000).toISOString(),
        note: 'Amit Kumar is out for delivery. Share 4-digit PIN 1947 at doorstep.',
        actor: 'Amit Kumar',
      },
    ],
  },
  {
    id: 'FF-51920',
    user_id: 'user_cust_01',
    customer_name: 'Aditi Sharma',
    customer_phone: '+91 98450 12345',
    address: INITIAL_ADDRESSES[1],
    status: 'DELIVERED',
    bag_id: 'BAG-1002',
    measured_weight_kg: 6.0,
    items: [
      {
        id: 'item_4',
        service_id: 'srv_wash_fold',
        service_name: 'Wash & Eco-Fold',
        quantity: 1,
        weight: 6.0,
        unit_price: 69,
        total_price: 414,
      },
    ],
    subtotal: 414,
    discount_amount: 0,
    delivery_charge: 0,
    express_surcharge: 0,
    total_amount: 414,
    payment_status: 'PAID',
    payment_method: 'cod',
    loyalty_points_used: 0,
    loyalty_points_earned: 41,
    pickup_slot_date: '5 days ago',
    pickup_slot_time: '9:00 AM',
    estimated_delivery: '4 days ago',
    delivery_pin: '5512',
    created_at: new Date(Date.now() - 3600000 * 120).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 96).toISOString(),
    history: [
      { id: 'h4_1', status: 'ORDER_PLACED', timestamp: new Date(Date.now() - 3600000 * 120).toISOString() },
      { id: 'h4_2', status: 'DELIVERED', timestamp: new Date(Date.now() - 3600000 * 96).toISOString(), note: 'Verified by OTP/PIN at delivery' },
    ],
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    code: 'FRESH50',
    discount_type: 'percentage',
    discount_value: 50,
    min_order: 200,
    max_discount: 150,
    description: '50% off up to ₹150 on your first 3 bookings',
  },
  {
    code: 'CLEAN100',
    discount_type: 'fixed',
    discount_value: 100,
    min_order: 300,
    description: 'Flat ₹100 instant cash discount above ₹300',
  },
  {
    code: 'FIRSTWASH',
    discount_type: 'fixed',
    discount_value: 40,
    min_order: 150,
    description: 'Zero delivery fees on all orders',
  },
];

export const INITIAL_SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'sub_student',
    name: 'Student Bag Pass',
    price: 899,
    period: 'month',
    max_kg: 15,
    free_pickups: 2,
    features: [
      'Up to 15 kg Wash & Fold',
      '2 Free scheduled pickups',
      'Standard 48-hr turnaround',
      'Zero delivery surcharges',
    ],
  },
  {
    id: 'sub_family',
    name: 'Family Fresh Pass',
    price: 2199,
    period: 'month',
    max_kg: 40,
    free_pickups: 5,
    recommended: true,
    features: [
      'Up to 40 kg Wash & Fold or Steam Press',
      '5 Weekly scheduled pickups',
      'Fast 24-hr turnaround guaranteed',
      'Free antimicrobial sanitize bath',
      'Priority customer hotline',
    ],
  },
  {
    id: 'sub_executive',
    name: 'Executive Crisp Pass',
    price: 3499,
    period: 'month',
    max_kg: 60,
    free_pickups: 8,
    features: [
      'Up to 60 kg laundry & ironing',
      'Includes 5 Free Artisan Dry Clean garments',
      'Same-day Express delivery included',
      'Complimentary custom garment bags',
    ],
  },
];

export const INITIAL_LOYALTY: LoyaltyAccount = {
  user_id: 'user_cust_01',
  balance: 380, // 380 points = ₹3.80 discount
  history: [
    { id: 'lp_1', type: 'earned', points: 26, description: 'Order FF-74102', date: 'Today' },
    { id: 'lp_2', type: 'earned', points: 55, description: 'Order FF-63914', date: 'Yesterday' },
    { id: 'lp_3', type: 'earned', points: 300, description: 'Welcome Bonus', date: 'Last week' },
  ],
};

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'TCK-104',
    user_id: 'user_cust_01',
    order_id: 'FF-63914',
    subject: 'Special instruction reminder for silk blouse',
    category: 'general',
    message: 'Please ensure cold water wash only for the maroon silk blouse included in the load.',
    status: 'in_progress',
    priority: 'medium',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
    resolution: 'Instruction flagged to Facility Lead Sunita Patel.',
  },
];
